### ISSUE TITLE
wingpanel-bzr not working properly

### ISSUE THREAD

**Issue by rkmax** [alucryd/aur-alucryd#11]
I've installed all packages for a full working pantheon in my Arch with GDM.

Wingpanel only show the Applications launcher and the Close, Shutdown, etc. menu but the menu is not working and the indicators aren't show

**Comment by alucryd** [comment]
Indicators all work now, having a bit of trouble with slingshot, but I think it's safe to say it's an upstream issue. Closing this ticket.
