### ISSUE TITLE
pantheon-default-settings invalid key

### ISSUE THREAD

**Issue by dsandstrom** [alucryd/aur-alucryd#16]
I'm not sure if this is where you want bug reports or on AUR.  I find github easier to use and you responded last time.  But, let me know what is better for you.

I was able to install, but now I receive this message when I use pacman.  I was able to edit the file mentioned, which seems to have fixed it on my system.  I deleted the line because I didn't see a terminal like key for my media keys.
```
No such key 'terminal' in schema 'org.gnome.settings-daemon.plugins.media-keys' as specified in override file 'usr/share/glib-2.0/schemas/25_pantheon-default-settings.gschema.override'; ignoring override for this key.
```

**Comment by alucryd** [comment]
Thx for the report. A while ago I'd have said that the AUR comment section was the better place for this, but since we are nearing a complete wipe with AUR 4.0, it doesn't really matter.

This message is completely harmless, but I should remove the key nonetheless. I'll do that next update.

**Comment by alucryd** [comment]
Fixed in my latest update.
