### ISSUE TITLE
[lightdm-pantheon-greeter] Fail to start with exit code 135

### ISSUE THREAD

**Issue by Firef0x** [alucryd/aur-alucryd#20]
Hello @alucryd ,

Appreciate your great job. I've installed `lightdm-pantheon-greeter` and enabled systemd service to trigger. But my system failed to start `lightdm-pantheon-greeter` with exit code 135. Here are some logs while executing `lightdm --test-mode -d`. Could you help me fixing this problem? Many thanks!

https://gist.github.com/Firef0x/e1c6ee479bf7747e85ca

Hope for your reply! :heart_eyes: 

Yours sincerely! :bow:

**Comment by alucryd** [comment]
Seems your indicators are the problem. Does it start if you uninstall them?
It works fine here with indicator-{datetime,session,sound}, I have them on my pantheon repo [1], maybe you could try with those.

[1] http://pkgbuild.com/~alucryd/pantheon/

**Comment by alucryd** [comment]
Should be fixed in bzr version, it doesn't rely on indicators anymore.

**Comment by Firef0x** [comment]
Hello @alucryd ,

Thx for your notification. However I gave up using `lightdm-pantheon-greeter`. Hope it helps anyone with the same problem.

Yours sincerely! :bow:
