### ISSUE TITLE
Gala wm possible bug

### ISSUE THREAD

**Issue by Ste74** [alucryd/aur-alucryd#24]
Hi @alucryd , I am the builder project of Manjaro pantheon .
First of all thank you for making this possible , without your work this would not be born .
Since the wingpanel still has problems I replaced it with budgie - panel but the session is pure pantheon .
Now we come to the bug . The package does not work with gala mutter 3.16 , must regress to 3.14 and then recompile gala from bzr ....
https://forum.manjaro.org/index.php?topic=22760.msg201306#msg201306

**Comment by alucryd** [comment]
I've been using gala with mutter 3.16 for a while now, I'm not sure what that post is about but I didn't encounter errors. In any case, if there's a bug, you should report that upstream, there's not much I can do about it.

**Comment by Ste74** [comment]
No infact only programs outside repo panheon not the controls works example midori and libreoffice ...
pantheon -files , terminal and other work ...
So tips on launchpad open issue ?

**Comment by alucryd** [comment]
Ok, in that case I can confirm the bug, doesn't happen all the time, but it's definitely there. Just head over to gala's launchpad and click report a bug, it's that easy. They'll want to hear about it since they introduced 3.16 support not long ago.

**Comment by Ste74** [comment]
Thanks alucryd of Your feedback I close this report ..
greetings
