### ISSUE TITLE
depends

### ISSUE THREAD

**Issue by SolarAquarion** [alucryd/aur-alucryd#28]
:: audience-bzr: requires libgranite.so=2-64
:: eidete-bzr: requires libgranite.so=2-64
:: footnote-bzr: requires libgranite.so=2-64
:: gala-bzr: requires libgranite.so=2-64
:: midori-granite-bzr: requires libgranite.so=2-64
:: pantheon-calculator-bzr: requires libgranite.so=2-64
:: pantheon-files-bzr: requires libgranite.so=2-64
:: pantheon-photos-bzr: requires libgranite.so=2-64

**Comment by alucryd** [comment]
There was a soname bump, and it was fixed before you filed this, you just have to force fetch those packages again because I have no means to bump the pkgrel on that repo.
