### ISSUE TITLE
Dota 2 Reborn which is the default now doesnt work.

### ISSUE THREAD

**Issue by 420git** [alucryd/aur-alucryd#30]
Dota 2 was working but Reborn wasnt and I always get the following error

failed to dlopen "librendersystemgl.so" error=libudev.so.0: wrong ELF class: ELFCLASS32
 failed to dlopen "libpangoft2-1.0.so" error=libpng12.so.0: wrong ELF class: ELFCLASS32
Plat_GetProcAddresses: unable to load 'libpangoft2-1.0.so'

Now that Dota 2 has moved to reborn I cant play it at all.
Is there something wrong with my system libs.
Note : I installed many of missing libs before I found your repo.
Im on 64 with multilib enabled.

**Comment by 420git** [comment]
Plz refer to this post I made on Arch BBS

https://bbs.archlinux.org/viewtopic.php?id=202231

**Comment by alucryd** [comment]
Well the error message says it all, my bet is Dota Reborn is native 64bit and wants 64bits libs. Install libpng12 and libudev0 and try again.

**Comment by alucryd** [comment]
New dota is indeed 64bit only (hallelujah), I've pushed libudev0 and libpng12 to my repo.

**Comment by 420git** [comment]
You were right
I had libudev.so and libudev.so.1 as symlinks to libudev.so.1.6.4 in lib64
in lib32 I have libudev.so and libudev.so.1 as symlinks to libudev.so.1.6.4 but I also have libudev.so.0 as symlink to libudev.so.0.13.1
Also libpng12 is missing from my lib64 but present in lib32.

After installing the missing libs it works. Thanks very much even valve support didnt point the problem which is very terrible.
