### ISSUE TITLE
wingpanel-bzr failed to launch

### ISSUE THREAD

**Issue by frozenxuan** [alucryd/aur-alucryd#33]
(error message)
[INFO 09:34:59.039891] Application.vala:155: System Panel version: 2.0
[INFO 09:34:59.040062] Application.vala:157: Kernel version: 4.2.3-1-ARCH
[FATAL 09:34:59.087943] [GLib] g_error_free: assertion 'error != NULL' failed
[ERROR 09:34:59.120021] [GLib-GIO] Settings schema 'org.pantheon.desktop.gala.notifications' does not contain a key named 'apps'
Trace/breakpoint trap (core dumped)

**Comment by Ste74** [comment]
Hi , see this workaround 
https://github.com/Ste74/pantupdate/blob/master/org.pantheon.desktop.gala.gschema.xml
copy this on 
/usr/share/glib-2.0/schemas/
and then do
glib-compile-schemas /usr/share/glib-2.0/schemas/

this workaround is made by quequotion ( thanks )
https://bbs.archlinux.org/viewtopic.php?pid=1568053#p1568053

**Comment by lijunle** [comment]
I get into the same problem... However, the error message is shown **only when** install wingpanel-bzr.

However, using @Ste74 's schema (as same as the code snippet in the post) does not work...

From my `25_pantheon-default-settings.gschema.override` file, the `apps` assign as a string array:

```ini
[org.pantheon.desktop.gala.notifications]
apps=['NetworkManager:show,on', 'Power:show,on']
```

So, change the `app` XML element to (type with `as` and default value as `[]`)

```xml
<key type="as" name="apps">
	<default>[]</default>
	<summary>Apps</summary>
</key>
```

After modifications, the upcoming steps are the same.

**Comment by alucryd** [comment]
There's really no need to bug me about this. This is clearly an upstream issue. Also using the old schema is the exact opposite of what you should be doing, ie make the apps compatible with the new schema. Plus this is most likely very easy to do, if only I had extra time on my hands.

**Comment by alucryd** [comment]
It's been fixed upstream. Closing the issue.
