### ISSUE TITLE
Cannot install pantheon-session-bzr

### ISSUE THREAD

**Issue by lijunle** [alucryd/aur-alucryd#34]
From [Arch wiki](https://wiki.archlinux.org/index.php/Pantheon#Installation), it is said to use your repo to install Pantheon. However, it fails because not find `gtk-engine-unico` package. I find [it in AUR](https://aur.archlinux.org/packages/gtk-engine-unico/). Could you please add it to your repo?

Install log:

```
lijunle@arch [01:32:13] [~] 
-> % sudo pacman -S pantheon-session-bzr
resolving dependencies...
:: There are 2 providers available for libgranite.so=3-64:
:: Repository community
   1) granite
:: Repository pantheon
   2) granite-bzr

Enter a number (default=1): 2
warning: cannot resolve "gtk-engine-unico", a dependency of "gtk-theme-elementary-bzr"
warning: cannot resolve "gtk-theme-elementary-bzr", a dependency of "pantheon-default-settings-bzr"
warning: cannot resolve "pantheon-default-settings-bzr", a dependency of "pantheon-session-bzr"
:: There are 2 providers available for libswitchboard-2.0.so=0-64:
:: Repository pantheon
   1) switchboard  2) switchboard-bzr

Enter a number (default=1): 2
:: The following package cannot be upgraded due to unresolvable dependencies:
      pantheon-session-bzr

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: gtk-theme-elementary-bzr: requires gtk-engine-unico
:: pantheon-default-settings-bzr: requires gtk-theme-elementary-bzr
:: pantheon-session-bzr: requires pantheon-default-settings-bzr
```

**Comment by alucryd** [comment]
GTk dropped all engine support as of 3.16 so they're not even loaded anymore. I will remove the dep when I have time, in the meantime you can do so locally.

**Comment by NicoHood** [comment]
How to do it manually? Will you still fix it?

**Comment by alucryd** [comment]
Apologies for the delay, just updated the PKGBUILD. That being said, you should be able to figure this out by yourself if you wish to use Arch Linux.

**Comment by NicoHood** [comment]
Thanks for patching it! It now installs without any problems.

You are right that arch is for advanced users. However you have to start at some point, so I wanted to start using arch with pantheon DE. I could install the packages so far, but have no idea to run the DE. If you could add a bit more information how to get pantheon running with gdm or lightdm, that'd be nice and also help a lot of people. I guess its not much steps to do, but it takes long to solve this puzzle for a beginner. Thanks for all ya work ;)
