### ISSUE TITLE
Pantheon-terminal-bzr depends on vte290

### ISSUE THREAD

**Issue by angiest** [alucryd/aur-alucryd#36]
The pantheon-terminal-bzr package has a dependency on vte290, which is no longer available from the official repositories, nor is it in the AUR.

**Comment by Ste74** [comment]
You can use the rollback machine of arch linux
http://ala.seblu.net/packages/v/vte290/
modify the pkgbuild ( add in source  bla bla) :)

**Comment by alucryd** [comment]
There's no need for the ARM, pantheon-terminal is now compatible with vte3.
