### ISSUE TITLE
Add ARM builds

### ISSUE THREAD

**Issue by NicoHood** [alucryd/aur-alucryd#38]
I tried to modify each `PKGBUILD` and added ` 'armv7h'`. However I get an error when I try to install `slingshot-launcher-bzr`:

```
==> Install or build missing dependencies for slingshot-launcher-bzr:
error: target not found: libwingpanel-2.0.so
error: target not found: libswitchboard-2.0.so
```

Is there any chance to see arm support or do they have to port more code upstream? Any ideas?

**Comment by alucryd** [comment]
I have no clue if ARM is even supported at all. You may want to ask upstream directly.

**Comment by alucryd** [comment]
Closing this, I don't have any means of supporting any ARM build, and I don't think upstream cares about ARM just yet.
