### ISSUE TITLE
wingpanel won't run

### ISSUE THREAD

**Issue by benwaffle** [alucryd/aur-alucryd#42]
`wingpanel: symbol lookup error: /usr/lib/wingpanel/libslingshot.so: undefined symbol: plank_unity_client_get_type`

**Comment by y2kbadbug** [comment]
I can confirm this.

**Comment by huiyiqun** [comment]
build `slingshot-launcher-bzr` from source fix this problem.

**Comment by alucryd** [comment]
wingpanel is pretty much useless right now, you should use wingpanel-bzr instead anyway.
