### ISSUE TITLE
steam-libs should depend on lib32-libappindicator-gtk2

### ISSUE THREAD

**Issue by benwaffle** [alucryd/aur-alucryd#45]
this fixes the missing tray icon with STEAM_RUNTIME=0, but building this dependency is a bit annoying

I have a working PKGBUILD for it but i can't push it to the AUR
https://github.com/benwaffle/lib32-libappindicator-AUR

**Comment by alucryd** [comment]
It's already in optdepends, I'm not making this a regular depends, tray icons and gtk2 are both ancient things of the past and should just die.

**Comment by benwaffle** [comment]
fair enough
