### ISSUE TITLE
pantheon session

### ISSUE THREAD

**Issue by SolarAquarion** [alucryd/aur-alucryd#46]
==> Making package: pantheon-session-bzr r65-1 (Tue Aug  9 18:21:14 EDT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Branching lp:~elementary-os/elementaryos/pantheon-xsession-settings...
You have not informed bzr of your Launchpad ID, and you must do this to
write to Launchpad or access private data.  See "bzr help launchpad-login".
Branched 76 revisions.                                                           
==> Validating source files with sha256sums...
    pantheon-session ... Skipped
==> Extracting sources...
  -> Creating working copy of pantheon-session bzr repo...
==> Starting prepare()...                                                        
sed: can't read autostart/polkit-gnome-authentication-agent-1-pantheon.desktop: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by alucryd** [comment]
Fixed in r77-1.
