### ISSUE TITLE
plank-bzr requires libdbusmenu-gtk3

### ISSUE THREAD

**Issue by libcg** [alucryd/aur-alucryd#47]
$ sudo pacman -S plank-bzr
    resolving dependencies...
    warning: cannot resolve "libdbusmenu-gtk3", a dependency of "plank-bzr"
    :: The following package cannot be upgraded due to unresolvable dependencies:
          plank-bzr
    
    :: Do you want to skip the above package for this upgrade? [y/N] n
    error: failed to prepare transaction (could not satisfy dependencies)
    :: plank-bzr: requires libdbusmenu-gtk3

Building the dependancy from AUR solved the issue

**Comment by alucryd** [comment]
I haven't updated plank-bzr on my repo for a long time, you're better off building it from AUR. I just deleted the remnants from my repo.
