### ISSUE TITLE
pcsx2-git illegal instructions

### ISSUE THREAD

**Issue by MinervaW1993** [alucryd/aur-alucryd#48]
Installing from alucryd repo. Gives me illegal instructions error.

uname -a:
Linux minerva 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux
 
journalctl:
11月 29 23:45:37 minerva kernel: traps: PCSX2[1033] trap invalid opcode ip:83d5803 sp:ffddb914 error:0 in PCSX2[8048000+53e000]
11月 29 23:45:37 minerva systemd[1]: Started Process Core Dump (PID 1034/UID 0).
11月 29 23:45:37 minerva systemd-coredump[1035]: Process 1033 (PCSX2) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 1033:
                                                  #0  0x00000000083d5803 n/a (PCSX2)
                                                  #1  0x000000000806c2a8 n/a (PCSX2)
                                                  #2  0x00000000083e284b n/a (PCSX2)
                                                  #3  0x00000000f6308126 __libc_start_main (libc.so.6)
                                                  #4  0x000000000806ca32 n/a (PCSX2)

**Comment by alucryd** [comment]
Those builds have advanced simd enabled, you need a recent cpu to use them. I don't want to disable it as it would decrease performances for a lot of people, please build pcsx2-git locally so it only uses what instructions your CPU does provide.
