### ISSUE TITLE
granite-bzr-r1045-1 not in repo resulting in pacman -Syu update failure.

### ISSUE THREAD

**Issue by jadesoturi** [alucryd/aur-alucryd#50]
```
sudo pacman -Syu
[sudo] password for jadesoturi: 
:: Synchronizing package databases...
 pantheon is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (52) boost-libs-1.63.0-2  brltty-5.5-2  chromium-58.0.3029.81-4  cryptsetup-1.7.5-1  cups-filters-1.13.5-1  enchant-1.6.1-2  evolution-data-server-3.24.1+5+g98589a27b-3  ffmpeg-1:3.3-5  ffmpeg2.8-2.8.11-6  gd-2.2.4-2  git-2.12.2-4  granite-bzr-r1045-1
              gst-plugins-bad-1.10.4-7  harfbuzz-1.4.5-2  harfbuzz-icu-1.4.5-2  hunspell-1.6.1-1  icu-59.1-1  imagemagick-6.9.8.4-2  js38-38.8.0-3  kdebase-runtime-17.04.0-2  lib32-dbus-1.10.18-1  lib32-harfbuzz-1.4.1-2  lib32-icu-59.1-1  lib32-libpciaccess-0.13.5-1
              lib32-libpsl-0.17.0-2  lib32-libwebp-0.6.0-1  lib32-sdl2_image-2.0.1-2  libcdr-0.1.3-3  libe-book-0.1.2-7  libfbclient-2.5.7.27050-2  libmspub-0.1.2-7  libphonenumber-8.4.1-2  libpsl-0.17.0-2  libreoffice-still-5.2.6-3
              libtracker-sparql-1.12.0+1+g922c213a5-2  libvisio-0.1.5-4  libwebp-0.6.0-1  libxml2-2.9.4+16+g07418011-2  ocl-icd-2.2.11-1  opencv-3.2.0-3  poppler-0.54.0-1  poppler-glib-0.54.0-1  python-setuptools-1:35.0.2-1  python2-setuptools-1:35.0.2-1  qt4-4.8.7-19
              qt5-base-5.8.0-11  raptor-2.0.15-6  sdl2_image-2.0.1-2  sonnet-5.33.0-2  tracker-1.12.0+1+g922c213a5-2  webkit2gtk-2.16.1-3  webkitgtk-2.4.11-6

Total Download Size:      0,28 MiB
Total Installed Size:  1285,45 MiB
Net Upgrade Size:        -1,09 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'granite-bzr-r1045-1-x86_64.pkg.tar.xz' from pkgbuild.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

```

According to Namarrgon on irc the repo only has granite-bzr-r1043-1-x86_64.pkg.tar.xz 

Please update :)

**Comment by jadesoturi** [comment]
sudo pacman -Syu
[sudo] password for jadesoturi: 
:: Synchronizing package databases...
 pantheon is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (52) boost-libs-1.63.0-2  brltty-5.5-2  chromium-58.0.3029.81-4  cryptsetup-1.7.5-1  cups-filters-1.13.5-1  enchant-1.6.1-2  evolution-data-server-3.24.1+5+g98589a27b-3  ffmpeg-1:3.3-5  ffmpeg2.8-2.8.11-6  gd-2.2.4-2  git-2.12.2-4  granite-bzr-r1045-1
              gst-plugins-bad-1.10.4-7  harfbuzz-1.4.5-2  harfbuzz-icu-1.4.5-2  hunspell-1.6.1-1  icu-59.1-1  imagemagick-6.9.8.4-2  js38-38.8.0-3  kdebase-runtime-17.04.0-2  lib32-dbus-1.10.18-1  lib32-harfbuzz-1.4.1-2  lib32-icu-59.1-1  lib32-libpciaccess-0.13.5-1
              lib32-libpsl-0.17.0-2  lib32-libwebp-0.6.0-1  lib32-sdl2_image-2.0.1-2  libcdr-0.1.3-3  libe-book-0.1.2-7  libfbclient-2.5.7.27050-2  libmspub-0.1.2-7  libphonenumber-8.4.1-2  libpsl-0.17.0-2  libreoffice-still-5.2.6-3
              libtracker-sparql-1.12.0+1+g922c213a5-2  libvisio-0.1.5-4  libwebp-0.6.0-1  libxml2-2.9.4+16+g07418011-2  ocl-icd-2.2.11-1  opencv-3.2.0-3  poppler-0.54.0-1  poppler-glib-0.54.0-1  python-setuptools-1:35.0.2-1  python2-setuptools-1:35.0.2-1  qt4-4.8.7-19
              qt5-base-5.8.0-11  raptor-2.0.15-6  sdl2_image-2.0.1-2  sonnet-5.33.0-2  tracker-1.12.0+1+g922c213a5-2  webkit2gtk-2.16.1-3  webkitgtk-2.4.11-6

Total Download Size:      0,28 MiB
Total Installed Size:  1285,45 MiB
Net Upgrade Size:        -1,09 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
error: failed retrieving file 'granite-bzr-r1045-1-x86_64.pkg.tar.xz' from pkgbuild.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
`

According to Namarrgon on irc the repo only has granite-bzr-r1043-1-x86_64.pkg.tar.xz 

Please update :)

**Comment by alucryd** [comment]
Forgot to close this, fixed it a while ago.
