### ISSUE TITLE
granite-git  0.5.r10.79c5018-1 error update

### ISSUE THREAD

**Issue by hackintosh1984pl** [alucryd/aur-alucryd#57]
I have install in system granite-git  0.4.1.r81.73d232f and now update error insalled to 0.5.r10.79c5018

$ yaourt -i granite-git
1 pantheon/granite-git 0.5.r10.79c5018-1 (pantheon-unstable) [installed: 0.4.1.r81.73d232f-1]

$ sudo pacman  -Syu granite-git
:: Synchronizowanie baz danych z pakietami…
 core jest aktualne
 extra jest aktualne
 community jest aktualne
 multilib jest aktualne
 pantheon jest aktualne                              0,0   B  0,00B/s 00:00 [------------------------------------------]   0%
:: Rozpoczynanie pełnej aktualizacji systemu…
rozwiązywanie zależności…
szukanie sprzecznych pakietów...
błąd:  nie udało się przygotować transakcji (nie udało się rozwiązać zależności)
:: eidete-bzr: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: gala-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: lightdm-pantheon-greeter-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: pantheon-applications-menu-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: pantheon-camera-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: pantheon-music-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: pantheon-videos-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: scratch-text-editor: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: switchboard-plug-applications-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: switchboard-plug-datetime-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: switchboard-plug-desktop-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: switchboard-plug-keyboard-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: wingpanel-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: wingpanel-indicator-datetime-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: wingpanel-indicator-network-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: wingpanel-indicator-notifications-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: wingpanel-indicator-power-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: wingpanel-indicator-session-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'
:: wingpanel-indicator-sound-git: instalacja granite-git (0.5.r10.79c5018-1) zależność przerw 'libgranite.so=3-64'

**Comment by alucryd** [comment]
granite 0.5 has had a soname bump compared to 0.4, you need to rebuild everything against the new one. You can force the installation of granite-git, then rebuild all pantheon git packages.

**Comment by alucryd** [comment]
Oh, looks like you're using my repo, in that case everything on it has been rebuilt and should install fine now.
