### ISSUE TITLE
warning: cannot resolve "libgranite.so=3-64", a dependency of *everything that's related to switchboard*

### ISSUE THREAD

**Issue by polyzium** [alucryd/aur-alucryd#59]
I decided to give Pantheon a shot. However after adding your repository i installed everything except the "Switchboard" thing (i assume?)
[Install log](https://gist.github.com/polyzium/d187ae364f4d09ea145682d53b0d18b1)

**Comment by alucryd** [comment]
The pantheon group is not usable yet, some packages don't have a stable version, and you'll get these kind of conflicts as a result. Please install the pantheon-unstable group instead.
