### ISSUE TITLE
For some reason some of the ports to meson hasn't been pushed to the aur proper

### ISSUE THREAD

**Issue by SolarAquarion** [alucryd/aur-alucryd#61]

**Comment by SolarAquarion** [comment]
@alucryd a bunch of the switchboard plugs have moved to meson, and can you move to arch-meson build instead of the mkdir build

**Comment by alucryd** [comment]
All should be in there now.

**Comment by SolarAquarion** [comment]
See you see my PR?

**Comment by alucryd** [comment]
Yes I did, and I'm not merging it. You still haven't learned that bumping pkgvers on git packages for the sake of bumping them is utterly useless, and you're not repecting what I've been doing for meson packages.
