### ISSUE TITLE
unable to satisfy dependency 'libgranite.so=5-64'

### ISSUE THREAD

**Issue by askazik** [alucryd/aur-alucryd#68]
Morning I have: unable to satisfy dependency 'libgranite.so=5-64' 
---
[ask@ask lib]$ sudo pacman -S pantheon-session-git
resolving dependencies...
:: There are 2 providers available for libswitchboard-2.0.so=0-64:
:: Repository pantheon
   1) switchboard  2) switchboard-git

Enter a number (default=1): 2
:: There are 2 providers available for libwingpanel-2.0.so=0-64:
:: Repository pantheon
   1) wingpanel  2) wingpanel-git

Enter a number (default=1): 2
looking for conflicting packages...
:: granite and granite-git are in conflict. Remove granite-git? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
**:: unable to satisfy dependency 'libgranite.so=5-64' required by gala-git
:: unable to satisfy dependency 'libgranite.so=5-64' required by switchboard-git
:: unable to satisfy dependency 'libgranite.so=5-64' required by wingpanel-git**
[ask@ask lib]$ 
[ask@ask granite-git]$ sudo pacman -Ss granite-git
pantheon/granite-git 0.5.r67.256b50c-1 (pantheon-unstable) [installed]
    Library that extends Gtk+
[ask@ask granite-git]$ sudo pacman -Qi granite-git
Name            : granite-git
Version         : 0.5.r67.256b50c-1
Description     : Library that extends Gtk+
Architecture    : x86_64
URL             : 
Licenses        : LGPL3
Groups          : pantheon-unstable
Provides        : granite  **libgranite.so=5-64**
Depends On      : cairo  gdk-pixbuf2  glib2  glibc  gtk3  libgee  pango
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : granite
Replaces        : granite-bzr
Installed Size  : 1436.00 KiB
Packager        : Maxime Gauduin 
Build Date      : Tue 05 Jun 2018 02:40:42 AM CEST
Install Date    : Tue 05 Jun 2018 10:47:27 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum

**Comment by alucryd** [comment]
Should be good now.
