### ISSUE TITLE
Increasing the Contractor

### ISSUE THREAD

**Issue by btd1337** [alucryd/aur-alucryd#73]
Hi @alucryd 

elementary by default has these options in Pantheon Files:

![screenshot from 2018-07-05 00-18-42](https://user-images.githubusercontent.com/11943860/42300980-639744ea-7fe9-11e8-8109-63c3a15df0b4.png)

but _Compress_, _Extract Here_ and _Send via Bluetooth_ need to be added to the `/ usr / share / contractor` folder.

We do not currently have these features after installing the packages from your repository.

To add is very simple., you only need to copy the files to this folder after the contractor has been installed.

Can you add this statement to the PKGBUILD?

The files are these:

[contractor-utils-extensions.zip](https://github.com/alucryd/aur-alucryd/files/2164801/contractor-utils-extensions.zip)

**Comment by alucryd** [comment]
I'm not including an arbitrary zip file in my packages. Where does upstream keep them?

**Comment by dcelasun** [comment]
This is the upstream: https://github.com/elementary/contractor

**Comment by alucryd** [comment]
Hmm no it's not? And if you mean those examples at the bottom, half the links don't even work, and the other half are random files across several git repositories. Again, I will not bundle a half-assed job like this. Feel free to make your own package, or nag upstream to make a decent job of providing them alongside contractor, or in a dedicated, official repository.

**Comment by quequotion** [comment]
@dcelasun try [file-roller-pantheon](https://github.com/quequotion/pantheon-bzr-qq/tree/master/file-roller-pantheon) (also available from the [AUR](https://aur.archlinux.org/packages/file-roller-pantheon/)) for 'Compress' and 'Extract Here' integration.

**Comment by btd1337** [comment]
@quequotion bzr?

**Comment by quequotion** [comment]
> bzr?

Historically, the pantheon packages were hosted on [Launchpad](https://launchpad.net/) in [Bazaar repositories](https://en.wikipedia.org/wiki/GNU_Bazaar). Now the project has (mostly) moved to github, but I have not yet renamed my repository.

**Comment by btd1337** [comment]
It would be nice update this name to avoid confusion.

**Comment by quequotion** [comment]
I'll get around to it; it's not just the name. Changing the name changes the URL; I'll need to update links in a lot of places (archlinux forums, youtube, PKGBUILDS). 

By the way, we are getting off topic and this issue can probably be closed anyway as packages are now available for the contracts.
