### ISSUE TITLE
Not provided: libgranite.so=4-64

### ISSUE THREAD

**Issue by btd1337** [alucryd/aur-alucryd#75]
Is it possible to correct this error by PKGBUILD?

```
!! While searching for solutions the following errors occurred:

:: Not provided: libgranite.so=4-64 but needed by switchboard-plug-notifications-git-r348.5717038-1
:: Not provided: libgranite.so=4-64 but needed by switchboard-plug-applications-git-r317.d241d8f-1
:: Not provided: libgranite.so=4-64 but needed by switchboard-plug-sharing-git-r200.23bb1e3-1
```

**Comment by dhiegoborges** [comment]
Is it possible to correct this error by PKGBUILD?
~~ initializing aurman...
~~ calculating solutions...

!! While searching for solutions the following errors occurred:
:: Not provided: libgranite.so=4-64 but needed by switchboard-plug-sharing-git-r200.23bb1e3-1

!! we could not find a solution
!! if you think that there should be one, rerun aurman with the --deep_search flag

**Comment by alucryd** [comment]
Fixed in the new repo: https://pkgbuild.com/~alucryd/extra-alucryd/x86_64/
