### ISSUE TITLE
You need to push the changes to the aur

### ISSUE THREAD

**Issue by SolarAquarion** [alucryd/aur-alucryd#81]

**Comment by SolarAquarion** [comment]
@alucryd i guess you're not maintaining repositories anymore?

**Comment by alucryd** [comment]
I still am, see https://wiki.archlinux.org/index.php/Pantheon

**Comment by SolarAquarion** [comment]
pantheon-files-bzr is seemingly still in the repository?

**Comment by alucryd** [comment]
that was a typo, it's actually the git version inside, it's fixed now

**Comment by SolarAquarion** [comment]
lol, you have both bzr and git now even though the bzr is a typo
