### ISSUE TITLE
I think you're going to need to package a libmutter-2.0

### ISSUE THREAD

**Issue by SolarAquarion** [alucryd/aur-alucryd#89]
Because certain packages need a certain version of libmutter or a generic mutter, or maybe just a symlinking of mutter-3.0 to provide "libmutter"

**Comment by SolarAquarion** [comment]
All you would need to do then is to remove the binaries of mutter, because gala and whatever uses libmutter as the backend?

**Comment by alucryd** [comment]
Don't worry I know how to package a library. However I want to know if upstream is ever going to support libmutter-3 before I waste time on providing outdated libraries for them.

**Comment by SolarAquarion** [comment]
sounds good, especially if it'll take a year before they want to support
libmutter3

**Comment by SolarAquarion** [comment]
@alucryd i guess the next part is to add the depends to the packages and start the build along with updating the AUR packages
