### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by InvisibleRasta** [alucryd/aur-alucryd#91]
Some packages are missing, how do i install?
`warning: cannot resolve "libgala.so=0-64", a dependency of "wingpanel"
warning: cannot resolve "libwingpanel-2.0.so=0-64", a dependency of "lightdm-pantheon-greeter"
warning: cannot resolve "libgala.so=0-64", a dependency of "wingpanel"
warning: cannot resolve "libwingpanel-2.0.so=0-64", a dependency of "pantheon-applications-menu"
warning: cannot resolve "libgala.so=0-64", a dependency of "wingpanel"
warning: cannot resolve "libgala.so=0-64", a dependency of "wingpanel"
warning: cannot resolve "libwingpanel-2.0.so=0-64", a dependency of "wingpanel-indicator-session"
`

**Comment by bbaserdem** [comment]
The packages are incompatible with the latest mutter version in arch; hence will not build (and are not provided in repo) You can downgrade mutter to 3.28 and build them yourself. Alucryd will not provide them without upstream providing gala / update mutter version.

**Comment by alucryd** [comment]
Made a package for libmutter2 until upstream stops supporting stupid distros like ubuntu.
