### ISSUE TITLE
Some key combinations do not work

### ISSUE THREAD

**Issue by budetisufu** [alucryd/aur-alucryd#96]
Good morning!
As the name suggests, some combinations do not work. For example, media keys, screenshots, user combinations. Has anyone already encountered this problem?

**Comment by alucryd** [comment]
Hmm, would you mind providing some context?

**Comment by budetisufu** [comment]
I can not assign a combination to run the script or run the program. She just hangs out with "New Accelerator ..."
I can not control the sound from the keyboard. (Fn + F10 /F11 /F12)
At the same time, I can control the windows, change the brightness of the screen.

**Comment by alucryd** [comment]
pantheon runs of top of a gnome session, the pantheon.session file has this exact command (gnome-session --session=pantheon), there's no other way to launch it if you want everything to work correctly.

**Comment by budetisufu** [comment]
Yes, I know, but still it is strange. Returning to the combinations, what about this?

**Comment by alucryd** [comment]
I don't even know what you're talking about, please take this upstream, I'm not a pantheon developer, I'm just packaging it.
