### ISSUE TITLE
Gala-git error compile. 

### ISSUE THREAD

**Issue by AdsonCicilioti** [alucryd/aur-alucryd#98]
I have the newly installed Arch. With Only Gnome installed.

I followed the Wiki and installed the Pantheon-session-git package using Yay.

In dependency checking I noticed that the required libmuter2 is> = 3.29 ... and what is installed and its repository is 3.28 ...
![image](https://user-images.githubusercontent.com/6278398/61575661-d7007280-aaa4-11e9-87df-582f0780ecd2.png)
I do not know if that's exactly what breaks the compilation.

Here is the code that reports the compile error:
```c
WindowManager.c: In function ‘gala_window_manager_gala_real_plugin_info’:
../gala/src/WindowManager.vala:1876:9: warning: function returns address of local variable [-Wreturn-local-addr]
 1876 |    return info;
      |         ^
WindowManager.c:12060:17: note: declared here
/usr/bin/ld: /tmp/gala.vgv2Ld.ltrans1.ltrans.o: na função "_gala_icon_group_drag_end_gala_drag_drop_action_drag_end":
<artificial>:(.text+0x8aec): referência não definida para "meta_screen_reorder_workspace"
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
==> ERRO: Uma falha ocorreu em build().
    Abortando...
Error making: gala-git
```

**Comment by alucryd** [comment]
It should build fine now, switched to a branch that has support for newer mutter.
